# Generated by Django 4.1.2 on 2023-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
