# Generated by Django 4.1.2 on 2023-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
