# Generated by Django 4.1.2 on 2023-09-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_appointment_patient_name_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Unknown Patient', max_length=100),
        ),
    ]
