# Generated by Django 4.1.2 on 2023-09-19 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_patientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('Critical', 'Critical'), ('Stable', 'Stable'), ('Under Observation', 'Under Observation')], max_length=50)),
                ('medications_treatments', models.TextField()),
                ('other_details', models.TextField()),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('nurse', models.ForeignKey(limit_choices_to={'user_type': 4}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
