# Generated by Django 4.1.2 on 2023-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_nursereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='services_rendered',
        ),
        migrations.AddField(
            model_name='invoice',
            name='medications_prescribed',
            field=models.ManyToManyField(to='hospital.medication'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=100),
        ),
    ]
